version: v2
reward_weights:
  base_penalty: 0.02
  portfolio_step_scale: 5.0
  step_return_scale: 10.0
  transaction_cost_penalty: 100.0
  blocked_action_penalty: 0.5
  invalid_action_penalty: 0.0
  idle_base: 0.008
  idle_step: 0.0
  idle_cap: 0.015
  idle_trend_threshold: 0.0
  idle_trend_scale: 0.0
  idle_trend_cap: 0.0
  idle_extra_after_steps: 0
  idle_extra_penalty: 0.0
  opportunity_scale: 0.0
  opportunity_cap: 0.0
  drawdown_threshold: 0.2
  drawdown_exp: 5.0
  drawdown_penalty_scale: 10.0
  sell_pnl_scale: 8.0
  sell_profit_bonus: 0.5
  sell_profit_bonus_scale: 10.0
  sell_loss_bonus: 0.1
  sell_trend_threshold: -0.003
  sell_trend_scale: 5.0
  sell_trend_cap: 0.3
  loss_aversion_scale: 2.0
  pnl_cost_ratio_scale: 0.0
  pnl_cost_ratio_cap: 5.0
  buy_bonus: 0.0
  buy_trend_threshold: 0.0
  buy_trend_scale: 0.0
  buy_trend_cap: 0.0
  buy_trend_penalty_scale: 0.0
  buy_trend_penalty_cap: 0.0
  signal_alignment_scale: 0.0
  signal_misalignment_scale: 0.0
  signal_alignment_cap: 0.5
  hold_step_penalty: 0.0
  hold_penalty_cap: 0.0
  max_positions_penalty: 1.0
  recent_trade_scale: 3.0
  min_hold_steps: 10
  trade_cooldown_steps: 10
  fee_penalty_scale: 7.0
  early_close_penalty: 0.2
  carry_bonus_scale: 4.0
  carry_bonus_cap: 0.5
  hold_pnl_step_scale: 5.0
  episode_pnl_bonus_scale: 10.0
  auto_exit_penalty: 0.3
  stop_loss_pct: 0.03
  take_profit_pct: 0.05
  stop_loss_penalty: 1.0
  take_profit_bonus: 0.5
  unrealized_drawdown_scale: 5.0
  unrealized_drawdown_cap: 0.5
  auto_exit_enabled: true
  max_hold_steps: 100
  entry_signal_threshold: 0.0025
  entry_volatility_cap: 0.0
  entry_momentum_ratio_threshold: 0.35
  sharpe_bonus_scale: 2.0
  sharpe_bonus_cap: 2.0
  manual_exit_bonus: 0.25
